sudo: required
services:
  - docker

before_install:
  - docker build -t tanguven/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run tanguven/react-test npm run test -- --coverage

after_success:
  - docker build -t tanguven/multi_client ./client
  - docker build -t tanguven/multi_nginx ./nginx
  - docker build -t tanguven/multi_server ./server
  - docker build -t tanguven/multi_worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tanguven/multi_client
  - docker push tanguven/multi_nginx
  - docker push tanguven/multi_server
  - docker push tanguven/multi_worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-515288342799"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 