apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # ReadWriteOnce | ReadOnlyMany | ReadWriteMany
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
